name: Vulnerability Report
description: File a vulnerability report.
title: "[Provide a short descriptive title]"
labels: ["vulnerability", "unconfirmed"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this vulnerability report!
  - type: textarea
    id: what-happened
    attributes:
      label: What vulnerability?
      description: What vulnerability did you discover?
      placeholder: Please describe the vulnerability and link known CVEs if possible.
      value: "Vulnerability discovered"
    validations:
      required: true
  - type: textarea
    id: logs
    attributes:
      label: Relevant log output
      description: Please copy and paste any relevant log output. This will be automatically formatted into code, so no need for backticks.
      render: shell
  - type: checkboxes
    id: terms
    attributes:
      label: Code of Conduct
      description: By submitting this issue, you agree to follow our [Code of Conduct](https://github.com/qbicsoftware/data-manager-app?tab=coc-ov-file).
      options:
        - label: I agree to follow this project's Code of Conduct
          required: true
